export const userType = {
  SIMPLE_CLIENT: 'SIMPLE_CLIENT',
  PREMIUM_CLIENT: 'PREMIUM_CLIENT',
  MASTER_CLIENT: 'MASTER_CLIENT',
  SIMPLE_SELLER: 'SIMPLE_SELLER',
  PREMIUM_SELLER: 'PREMIUM_SELLER',
  MASTER_SELLER: 'MASTER_SELLER',
  SIMPLE_ADMIN: 'SIMPLE_ADMIN',
  GENERAL_ADMIN: 'GENERAL_ADMIN',
  PRODUCT_ADMIN: 'PRODUCT_ADMIN',
  SELLER_ADMIN: 'SELLER_ADMIN',
  CLIENT_ADMIN: 'CLIENT_ADMIN',
  MASTER_ADMIN: 'MASTER_ADMIN'
};
